services:
  postgres:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale
    hostname: timescale
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "testPassword"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "timeseries"
